spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: kuchbhi@123
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql

project:
  image: image/
  #HibernateConfig

  data:
    jdbc:
      repositories:
        enabled: true

security:
  basic:
    enabled: false
  ignored: /**\dt


